GET http://127.0.0.1:5000/brands/ 
###
GET http://127.0.0.1:5000/brands/34
###
POST http://127.0.0.1:5000/brands/
Content-Type: application/json

    {
        "title": "Asus"
    }
###
PUT http://127.0.0.1:5000/brands/
Content-Type: application/json

    {
        "id": 34,
        "title": "Hator"
    }
###
DELETE http://127.0.0.1:5000/brands/19