GET http://127.0.0.1:5000/categories/ 
###
GET http://127.0.0.1:5000/categories/6
###
POST http://127.0.0.1:5000/categories/
Content-Type: application/json

    {
        "title": "Devices"
    }
###
PUT http://127.0.0.1:5000/categories/
Content-Type: application/json

    {
        "id": 6,
        "title": "Miscellanious"
    }
###
DELETE http://127.0.0.1:5000/categories/6