### Get half of elements 

GET http://127.0.0.1:5000/customers/part

### Paginate elements

GET http://127.0.0.1:5000/customers/?page=2&result=5

### Get single element by ID

GET http://127.0.0.1:5000/customers/10

### Create new element

POST http://127.0.0.1:5000/customers/
Content-Type: application/json

    {
        "full_name": "Taras Yaremiy",
        "password": "my-secret-password",
        "email": "t-yx.com"
    }

### Change element by ID

PUT http://127.0.0.1:5000/customers/
Content-Type: application/json

    {
        "id": 9,
        "full_name": "John Doe",
        "email": "johndoe@example.com"
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/customers/10