GET http://127.0.0.1:5000/items/ 
###
GET http://127.0.0.1:5000/items/47
###
POST http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "price": 200,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }
###
PUT http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "id": 47,
        "price": 2000,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }
###
DELETE http://127.0.0.1:5000/items/46