### Get half of elements 

GET http://127.0.0.1:5000/items/part

### Paginate elements

GET http://127.0.0.1:5000/items/?page=3&result=6 

### Get single element by ID

GET http://127.0.0.1:5000/items/47

### Create new element

POST http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "price": 200,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }

### Change element by ID

PUT http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "id": 47,
        "price": 2000,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/items/46