GET http://127.0.0.1:5000/models/ 
###
GET http://127.0.0.1:5000/models/22
###
POST http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "title": "HP440",
        "brandId": 19
    }
###
PUT http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "id": 34,
        "title": "new title"
    }
###
DELETE http://127.0.0.1:5000/models/34