### Paginate elements

GET http://127.0.0.1:5000/models/?page=3&result=6 

### Get single element by ID

GET http://127.0.0.1:5000/models/22

### Create new element

POST http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "title": "HP440",
        "brandId": 19
    }

### Change element by ID

PUT http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "id": 34,
        "title": "new title"
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/models/34