GET http://127.0.0.1:5000/models/ 
###
GET http://127.0.0.1:5000/models/34
###
POST http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "title": "asdfgk"
    }
###
PUT http://127.0.0.1:5000/models/
Content-Type: application/json

    {
        "id": 34,
        "title": "new title"
    }
###
DELETE http://127.0.0.1:5000/models/34