GET http://127.0.0.1:5000/stores/ 
###
GET http://127.0.0.1:5000/stores/5
###
POST http://127.0.0.1:5000/stores/
Content-Type: application/json

    {
        "title": "Test Store"
    }
###
PUT http://127.0.0.1:5000/stores/
Content-Type: application/json

    {
        "id": 5,
        "title": "Altered Store"
    }
###
DELETE http://127.0.0.1:5000/stores/5