### Get half of elements 

GET http://127.0.0.1:5000/brands/part

### Get elements by attribute name

GET http://127.0.0.1:5000/brands/attr?id=3&&title=Intel

### Paginate elements

GET http://127.0.0.1:5000/brands?page=1&result=100

### Get single element by ID

GET http://127.0.0.1:5000/brands/20

### Create new element

POST http://127.0.0.1:5000/brands/
Content-Type: application/json

    {
        "title": "Asus"
    }

### Change element by ID

PUT http://127.0.0.1:5000/brands/
Content-Type: application/json

    {
        "id": 20,
        "title": "Hator"
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/brands/19