### Get half of elements 

GET http://127.0.0.1:5000/items/part

### Get elements by attribute name

GET http://127.0.0.1:5000/items/attr?category=Sports&brand=Samsung&brand=Intel&id=2

### Get filtered items

GET http://127.0.0.1:5000/items/filter?type=TV

### Paginate elements

GET http://127.0.0.1:5000/items/?page=1&result=60 

### Get single element by ID

GET http://127.0.0.1:5000/items/14

### Create new element

POST http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "price": 200,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }

### Change element by ID

PUT http://127.0.0.1:5000/items/
Content-Type: application/json

    {
        "id": 47,
        "price": 2000,
        "amount": 1,
        "brandId": 1,
        "modelId": 1,
        "categoryId": 1,
        "typeId": 1,
        "storeId": 1
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/items/46