###
// количество моделей каждого бренда
GET http://127.0.0.1:5000/misc/modelsByBrands

###
// количество товаров КАЖДОГО типа на каждом из складов
GET http://127.0.0.1:5000/misc/reviewStores

###
// имя покупателя, сделавшего больше всех покупок
GET http://127.0.0.1:5000/misc/topOrders

###
//имя покупателя, сделавшего самую дорогую покупку
GET http://127.0.0.1:5000/misc/topPrice