### Get half of elements 

GET http://127.0.0.1:5000/types/part

### Paginate elements

GET http://127.0.0.1:5000/types/?page=1&result=3

### Get single element by ID

GET http://127.0.0.1:5000/types/10

### Create new element

POST http://127.0.0.1:5000/types/
Content-Type: application/json

    {
        "title": "Test Type"
    }

### Change element by ID

PUT http://127.0.0.1:5000/types/
Content-Type: application/json

    {
        "id": 10,
        "title": "Altered Type",
        "description": 1
    }

### Delete element by ID

DELETE http://127.0.0.1:5000/types/10