module.exports = [
    {
      "categoryId": 1,
      "typeId": 1,
      "brandId": 1,
      "modelId": 1,
      "price": 22000,
      "storeId": 1,
      "amount": 65,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 1,
      "typeId": 1,
      "brandId": 2,
      "modelId": 2,
      "price": 24000,
      "storeId": 1,
      "amount": 40,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 1,
      "typeId": 2,
      "brandId": 3,
      "modelId": 3,
      "price": 3900,
      "storeId": 4,
      "amount": 240,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 1,
      "typeId": 2,
      "brandId": 3,
      "modelId": 4,
      "price": 4500,
      "storeId": 3,
      "amount": 510,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 1,
      "typeId": 2,
      "brandId": 4,
      "modelId": 5,
      "price": 6200,
      "storeId": 3,
      "amount": 120,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 3,
      "brandId": 5,
      "modelId": 6,
      "price": 53000,
      "storeId": 2,
      "amount": 1200,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 3,
      "brandId": 5,
      "modelId": 7,
      "price": 3000,
      "storeId": 2,
      "amount": 350,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 3,
      "brandId": 6,
      "modelId": 8,
      "price": 7500,
      "storeId": 4,
      "amount": 1400,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 4,
      "brandId": 7,
      "modelId": 9,
      "price": 19000,
      "storeId": 4,
      "amount": 100,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 4,
      "brandId": 1,
      "modelId": 10,
      "price": 21000,
      "storeId": 2,
      "amount": 120,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 2,
      "typeId": 4,
      "brandId": 8,
      "modelId": 11,
      "price": 18500,
      "storeId": 2,
      "amount": 50,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 3,
      "typeId": 5,
      "brandId": 9,
      "modelId": 12,
      "price": 23000,
      "storeId": 1,
      "amount": 150,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 3,
      "typeId": 5,
      "brandId": 9,
      "modelId": 13,
      "price": 2000,
      "storeId": 1,
      "amount": 60,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 3,
      "typeId": 5,
      "brandId": 10,
      "modelId": 14,
      "price": 5500,
      "storeId": 1,
      "amount": 220,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 3,
      "typeId": 6,
      "brandId": 11,
      "modelId": 15,
      "price": 3200,
      "storeId": 1,
      "amount": 400,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 3,
      "typeId": 6,
      "brandId": 12,
      "modelId": 16,
      "price": 2800,
      "storeId": 1,
      "amount": 320,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 4,
      "typeId": 7,
      "brandId": 13,
      "modelId": 17,
      "price": 6100,
      "storeId": 3,
      "amount": 180,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 4,
      "typeId": 7,
      "brandId": 14,
      "modelId": 18,
      "price": 3800,
      "storeId": 3,
      "amount": 135,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 4,
      "typeId": 8,
      "brandId": 15,
      "modelId": 19,
      "price": 2500,
      "storeId": 2,
      "amount": 200,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 4,
      "typeId": 8,
      "brandId": 16,
      "modelId": 20,
      "price": 3000,
      "storeId": 2,
      "amount": 530,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 4,
      "typeId": 8,
      "brandId": 17,
      "modelId": 21,
      "price": 4800,
      "storeId": 2,
      "amount": 180,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      "categoryId": 5,
      "typeId": 9,
      "brandId": 18,
      "modelId": 22,
      "price": 28000,
      "storeId": 4,
      "amount": 35,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]